"""Configurable parameter schema for the web UI."""

from __future__ import annotations

from src.api.models import ParamFieldSchema, ParamPresetSchema, ParamSchemaResponse, RunParams

DEV_PRESET_VALUES: dict = {
    "target_accuracy": 0.85,
    "min_macro_iter": 1,
    "max_macro_iter": 1000,
    "consecutive_pass_rounds": 1,
    "first_round_total_questions": 50,
    "focused_round_questions": 30,
    "questions_per_persona": 5,
    "use_chapter_mastery": True,
    "chapter_mastery_accuracy": 0.98,
    "short_term_notes_max_chars": 6000,
    "study_notes_target_ratio": 1.75,
    "study_notes_hard_max_chars": 50000,
    "student_material_study_max_chars": 6000,
    "long_term_notes_max_chars": 6000,
    "chapter_review_ratio": 0.1,
    "exam_long_term_ratio": 0.05,
    "exam_working_layer_ratio": 0.90,
    "reinforce_pool_ratio": 0.5,
    "student_notes_max_chars": 6000,
    "evidence_cap_score": 0.88,
    "judge_semantic_lenient": True,
    "judge_temperature": 0.2,
    "student_exam_temperature": 0.25,
    "crawl_max_pages": 0,
    "crawl_include_images": False,
    "judge_batch_size": 20,
    "student_answer_batch_size": 20,
    "max_validate_rounds": 1,
}

PROD_PRESET_VALUES: dict = {
    "target_accuracy": 0.95,
    "min_macro_iter": 3,
    "max_macro_iter": 1000,
    "consecutive_pass_rounds": 2,
    "first_round_total_questions": 150,
    "focused_round_questions": 50,
    "questions_per_persona": 10,
    "use_chapter_mastery": True,
    "chapter_mastery_accuracy": 0.98,
    "short_term_notes_max_chars": 6000,
    "study_notes_target_ratio": 1.75,
    "study_notes_hard_max_chars": 50000,
    "student_material_study_max_chars": 6000,
    "long_term_notes_max_chars": 6000,
    "chapter_review_ratio": 0.1,
    "exam_long_term_ratio": 0.05,
    "exam_working_layer_ratio": 0.90,
    "reinforce_pool_ratio": 0.5,
    "student_notes_max_chars": 6000,
    "evidence_cap_score": 0.88,
    "judge_semantic_lenient": True,
    "judge_temperature": 0.2,
    "student_exam_temperature": 0.25,
    "crawl_max_pages": 0,
    "crawl_include_images": True,
    "judge_batch_size": 10,
    "student_answer_batch_size": 10,
    "max_validate_rounds": 3,
}


def get_param_schema() -> ParamSchemaResponse:
    defaults = RunParams(urls=["https://example.com"])
    d = defaults.model_dump()
    fields = [
        ParamFieldSchema(
            key="goal",
            label="学习目标",
            description="描述学生应掌握的知识范围",
            type="text",
            default=d["goal"],
            group="任务",
        ),
        ParamFieldSchema(
            key="crawl_enabled",
            label="站点爬取",
            description="自动发现手册/文档子页面",
            type="bool",
            default=d["crawl_enabled"],
            group="任务",
        ),
        ParamFieldSchema(
            key="crawl_max_pages",
            label="最大爬取页数",
            description="0 = 自动抓取链接探测到的全部小节；>0 则限制抓取数量（手册站按目录叶子页计数）",
            type="int",
            default=d["crawl_max_pages"],
            min=0,
            max=500,
            group="任务",
        ),
        ParamFieldSchema(
            key="target_accuracy",
            label="目标正确率",
            description="加权正确率达到此值且满足最少轮次后可成功结束",
            type="float",
            default=d["target_accuracy"],
            min=0.5,
            max=1.0,
            step=0.01,
            group="循环",
        ),
        ParamFieldSchema(
            key="min_macro_iter",
            label="最少宏观轮次",
            description="至少完成的学习迭代次数",
            type="int",
            default=d["min_macro_iter"],
            min=1,
            max=100,
            group="循环",
        ),
        ParamFieldSchema(
            key="max_macro_iter",
            label="最大宏观轮次",
            description="硬上限，防止无限循环",
            type="int",
            default=d["max_macro_iter"],
            min=1,
            max=10000,
            group="循环",
        ),
        ParamFieldSchema(
            key="consecutive_pass_rounds",
            label="连续达标轮次",
            description="连续多少轮达到目标正确率才算 success",
            type="int",
            default=d["consecutive_pass_rounds"],
            min=1,
            max=20,
            group="循环",
        ),
        ParamFieldSchema(
            key="first_round_total_questions",
            label="首轮总题量",
            description="第一次宏观迭代的考试题数",
            type="int",
            default=d["first_round_total_questions"],
            min=10,
            max=500,
            group="考试",
        ),
        ParamFieldSchema(
            key="focused_round_questions",
            label="聚焦轮题量",
            description="后续宏观迭代的考试题数",
            type="int",
            default=d["focused_round_questions"],
            min=10,
            max=300,
            group="考试",
        ),
        ParamFieldSchema(
            key="questions_per_persona",
            label="每角色题数",
            description="五个出题角色各自每批出题数量",
            type="int",
            default=d["questions_per_persona"],
            min=1,
            max=30,
            group="考试",
        ),
        ParamFieldSchema(
            key="max_validate_rounds",
            label="出题自检轮数",
            description="Persona 出题失败时最多重试次数",
            type="int",
            default=d["max_validate_rounds"],
            min=1,
            max=5,
            group="考试",
        ),
        ParamFieldSchema(
            key="student_answer_batch_size",
            label="作答批大小",
            description="每次 LLM 作答的题目数",
            type="int",
            default=d["student_answer_batch_size"],
            min=1,
            max=50,
            group="考试",
        ),
        ParamFieldSchema(
            key="closed_book_exam",
            label="闭卷考试",
            description="作答时仅允许使用笔记，不给原文",
            type="bool",
            default=d["closed_book_exam"],
            group="学习真实性",
        ),
        ParamFieldSchema(
            key="use_chapter_mastery",
            label="章节掌握模式",
            description="按章节学习：单章闭卷达标后再学下一章（推荐）",
            type="bool",
            default=d.get("use_chapter_mastery", True),
            group="学习真实性",
        ),
        ParamFieldSchema(
            key="chapter_mastery_accuracy",
            label="章节掌握门槛",
            description="本章闭卷加权正确率达到此值才巩固进长期记忆并进入下一章",
            type="float",
            default=d.get("chapter_mastery_accuracy", 0.98),
            min=0.5,
            max=1.0,
            step=0.01,
            group="学习真实性",
            visible_when_key="use_chapter_mastery",
            visible_when_equals=True,
        ),
        ParamFieldSchema(
            key="student_material_study_max_chars",
            label="学习资料上下文上限",
            description="学习阶段每次喂给学生的本章/窗口资料最大字数（不含长期记忆与旧笔记）",
            type="int",
            default=d.get("student_material_study_max_chars", 6000),
            min=1000,
            max=100000,
            group="记忆与闭卷",
            visible_when_key="use_chapter_mastery",
            visible_when_equals=True,
        ),
        ParamFieldSchema(
            key="short_term_notes_max_chars",
            label="工作笔记基准下限",
            description="工作笔记篇幅下限；实际目标 ≈ 资料字数 × 笔记目标倍率，且不超过笔记硬上限",
            type="int",
            default=d.get("short_term_notes_max_chars", 4000),
            min=500,
            max=50000,
            group="记忆与闭卷",
            visible_when_key="use_chapter_mastery",
            visible_when_equals=True,
        ),
        ParamFieldSchema(
            key="study_notes_target_ratio",
            label="笔记目标倍率",
            description="笔记目标篇幅 ≈ 学习资料字数 × 此倍率（1.5–2.0，默认 1.75；同章修订时不低于已有笔记篇幅）",
            type="float",
            default=d.get("study_notes_target_ratio", 1.75),
            min=1.5,
            max=2.0,
            step=0.05,
            group="记忆与闭卷",
            visible_when_key="use_chapter_mastery",
            visible_when_equals=True,
        ),
        ParamFieldSchema(
            key="study_notes_hard_max_chars",
            label="工作笔记硬上限",
            description="单章工作笔记（short_term_notes）允许的最大字数，与闭卷总预算相互独立",
            type="int",
            default=d.get("study_notes_hard_max_chars", 50000),
            min=5000,
            max=100000,
            group="记忆与闭卷",
            visible_when_key="use_chapter_mastery",
            visible_when_equals=True,
        ),
        ParamFieldSchema(
            key="long_term_notes_max_chars",
            label="长期记忆总容量",
            description=(
                "章节掌握后写入的内化摘要总容量（仅闭卷考试使用）。"
                "设为 0 则关闭长期记忆存储；学习阶段不会注入长期记忆以节省上下文"
            ),
            type="int",
            default=d.get("long_term_notes_max_chars", 6000),
            min=0,
            max=50000,
            group="记忆与闭卷",
            visible_when_key="use_chapter_mastery",
            visible_when_equals=True,
        ),
        ParamFieldSchema(
            key="student_notes_max_chars",
            label="闭卷记忆总预算",
            description=(
                "闭卷时可用的记忆总字数（长期内化 + 工作参考层），不等于完整工作笔记长度。"
                "与上方「工作笔记硬上限」是不同参数，均可手动调整"
            ),
            type="int",
            default=d["student_notes_max_chars"],
            min=500,
            max=50000,
            group="记忆与闭卷",
        ),
        ParamFieldSchema(
            key="exam_long_term_ratio",
            label="闭卷·长期记忆占比",
            description=(
                "闭卷总预算中分配给「已掌握章节内化摘要」的比例。"
                "本章学习中当前章内容在闭卷时走「参考层」（工作笔记摘录），"
                "长期记忆通常仅含已掌握章节；可设为 0"
            ),
            type="float",
            default=d.get("exam_long_term_ratio", 0.05),
            min=0.0,
            max=0.95,
            step=0.01,
            group="记忆与闭卷",
            visible_when_key="use_chapter_mastery",
            visible_when_equals=True,
        ),
        ParamFieldSchema(
            key="exam_working_layer_ratio",
            label="闭卷·参考层占比",
            description=(
                "闭卷总预算中分配给「本章工作笔记摘录（术语/易错/自测）」的比例。"
                "同章多轮学习时闭卷主要依赖此项，建议 0.90–0.95；"
                "与长期记忆之和超过 95% 时会被自动调低"
            ),
            type="float",
            default=d.get("exam_working_layer_ratio", 0.90),
            min=0.0,
            max=0.95,
            step=0.01,
            group="记忆与闭卷",
            visible_when_key="use_chapter_mastery",
            visible_when_equals=True,
        ),
        ParamFieldSchema(
            key="chapter_review_ratio",
            label="复习题比例",
            description="页数模式下考试中复习题占比；章节掌握模式下本章未掌握时不跨章复习",
            type="float",
            default=d.get("chapter_review_ratio", 0.1),
            min=0.0,
            max=0.5,
            step=0.01,
            group="学习真实性",
            visible_when_key="use_chapter_mastery",
            visible_when_equals=True,
        ),
        ParamFieldSchema(
            key="reinforce_pool_ratio",
            label="错题巩固占比",
            description="每批考试中来自上轮错题复测的比例（前几轮自动略提高）",
            type="float",
            default=d.get("reinforce_pool_ratio", 0.5),
            min=0.1,
            max=0.8,
            step=0.01,
            group="学习真实性",
            visible_when_key="use_chapter_mastery",
            visible_when_equals=True,
        ),
        ParamFieldSchema(
            key="student_notes_study_max_chars",
            label="学习笔记上限（页数模式）",
            description="仅「页数课程模式」下每轮笔记最大长度",
            type="int",
            default=d["student_notes_study_max_chars"],
            min=1000,
            max=50000,
            group="记忆与闭卷",
            visible_when_key="use_chapter_mastery",
            visible_when_equals=False,
        ),
        ParamFieldSchema(
            key="curriculum_pages_per_round",
            label="每轮解锁页数（页数模式）",
            description="仅「页数课程模式」：每轮累积解锁的文档页面数",
            type="int",
            default=d["curriculum_pages_per_round"],
            min=1,
            max=200,
            group="学习真实性",
            visible_when_key="use_chapter_mastery",
            visible_when_equals=False,
        ),
        ParamFieldSchema(
            key="judge_evidence_only",
            label="Evidence 评分",
            description="Judge 仅依据 evidence 原文评分",
            type="bool",
            default=d["judge_evidence_only"],
            group="评分",
        ),
        ParamFieldSchema(
            key="evidence_cap_score",
            label="外推惩罚上限",
            description="语义宽松模式下，仅对明显编造才封顶；默认 0.88",
            type="float",
            default=d["evidence_cap_score"],
            min=0.5,
            max=1.0,
            step=0.01,
            group="评分",
        ),
        ParamFieldSchema(
            key="judge_semantic_lenient",
            label="语义宽松判分",
            description="开启后 Judge 以中心意思为准，跳过词面 evidence_cap；关闭则启用词面外推惩罚",
            type="bool",
            default=d.get("judge_semantic_lenient", True),
            group="评分",
        ),
        ParamFieldSchema(
            key="judge_temperature",
            label="Judge 温度",
            description="评分随机性：0=最稳定；0.2 左右适合语义判题；过高会导致同义答法波动",
            type="float",
            default=d.get("judge_temperature", 0.2),
            min=0.0,
            max=1.5,
            step=0.05,
            group="评分",
        ),
        ParamFieldSchema(
            key="student_exam_temperature",
            label="学生作答温度",
            description="闭卷/开卷作答时的随机性：越低越稳定，越高表述越多样",
            type="float",
            default=d.get("student_exam_temperature", 0.25),
            min=0.0,
            max=1.5,
            step=0.05,
            group="评分",
        ),
        ParamFieldSchema(
            key="judge_batch_size",
            label="Judge 批大小",
            description="每次 LLM 评分的题目数",
            type="int",
            default=d["judge_batch_size"],
            min=1,
            max=50,
            group="评分",
        ),
    ]
    groups = []
    for f in fields:
        if f.group not in groups:
            groups.append(f.group)

    presets = [
        ParamPresetSchema(
            id="development",
            label="开发调试",
            description="少题量、大批次、快速迭代（默认）",
            values=DEV_PRESET_VALUES,
        ),
        ParamPresetSchema(
            id="production",
            label="生产完整",
            description="150 题首轮、完整自检，接近真实学习闭环",
            values=PROD_PRESET_VALUES,
        ),
    ]
    return ParamSchemaResponse(
        groups=groups,
        fields=fields,
        presets=presets,
        default_preset="development",
    )
