"""Configurable parameter schema for the web UI."""

from __future__ import annotations

from src.api.models import ParamFieldSchema, ParamPresetSchema, ParamSchemaResponse, RunParams

DEV_PRESET_VALUES: dict = {
    "target_accuracy": 0.85,
    "min_macro_iter": 1,
    "max_macro_iter": 1000,
    "consecutive_pass_rounds": 1,
    "first_round_total_questions": 50,
    "focused_round_questions": 30,
    "questions_per_persona": 5,
    "use_chapter_mastery": True,
    "chapter_mastery_accuracy": 0.98,
    "short_term_notes_max_chars": 4000,
    "long_term_notes_max_chars": 6000,
    "chapter_review_ratio": 0.1,
    "exam_long_term_ratio": 0.65,
    "exam_working_layer_ratio": 0.30,
    "crawl_max_pages": 0,
    "crawl_include_images": False,
    "judge_batch_size": 20,
    "student_answer_batch_size": 20,
    "max_validate_rounds": 1,
}

PROD_PRESET_VALUES: dict = {
    "target_accuracy": 0.95,
    "min_macro_iter": 3,
    "max_macro_iter": 1000,
    "consecutive_pass_rounds": 2,
    "first_round_total_questions": 150,
    "focused_round_questions": 50,
    "questions_per_persona": 10,
    "use_chapter_mastery": True,
    "chapter_mastery_accuracy": 0.98,
    "short_term_notes_max_chars": 4000,
    "long_term_notes_max_chars": 6000,
    "chapter_review_ratio": 0.1,
    "exam_long_term_ratio": 0.65,
    "exam_working_layer_ratio": 0.30,
    "crawl_max_pages": 0,
    "crawl_include_images": True,
    "judge_batch_size": 10,
    "student_answer_batch_size": 10,
    "max_validate_rounds": 3,
}


def get_param_schema() -> ParamSchemaResponse:
    defaults = RunParams(urls=["https://example.com"])
    d = defaults.model_dump()
    fields = [
        ParamFieldSchema(
            key="goal",
            label="学习目标",
            description="描述学生应掌握的知识范围",
            type="text",
            default=d["goal"],
            group="任务",
        ),
        ParamFieldSchema(
            key="crawl_enabled",
            label="站点爬取",
            description="自动发现手册/文档子页面",
            type="bool",
            default=d["crawl_enabled"],
            group="任务",
        ),
        ParamFieldSchema(
            key="crawl_max_pages",
            label="最大爬取页数",
            description="0 = 自动抓取链接探测到的全部小节；>0 则限制抓取数量（手册站按目录叶子页计数）",
            type="int",
            default=d["crawl_max_pages"],
            min=0,
            max=500,
            group="任务",
        ),
        ParamFieldSchema(
            key="target_accuracy",
            label="目标正确率",
            description="加权正确率达到此值且满足最少轮次后可成功结束",
            type="float",
            default=d["target_accuracy"],
            min=0.5,
            max=1.0,
            group="循环",
        ),
        ParamFieldSchema(
            key="min_macro_iter",
            label="最少宏观轮次",
            description="至少完成的学习迭代次数",
            type="int",
            default=d["min_macro_iter"],
            min=1,
            max=100,
            group="循环",
        ),
        ParamFieldSchema(
            key="max_macro_iter",
            label="最大宏观轮次",
            description="硬上限，防止无限循环",
            type="int",
            default=d["max_macro_iter"],
            min=1,
            max=10000,
            group="循环",
        ),
        ParamFieldSchema(
            key="consecutive_pass_rounds",
            label="连续达标轮次",
            description="连续多少轮达到目标正确率才算 success",
            type="int",
            default=d["consecutive_pass_rounds"],
            min=1,
            max=20,
            group="循环",
        ),
        ParamFieldSchema(
            key="first_round_total_questions",
            label="首轮总题量",
            description="第一次宏观迭代的考试题数",
            type="int",
            default=d["first_round_total_questions"],
            min=10,
            max=500,
            group="考试",
        ),
        ParamFieldSchema(
            key="focused_round_questions",
            label="聚焦轮题量",
            description="后续宏观迭代的考试题数",
            type="int",
            default=d["focused_round_questions"],
            min=10,
            max=300,
            group="考试",
        ),
        ParamFieldSchema(
            key="questions_per_persona",
            label="每角色题数",
            description="五个出题角色各自每批出题数量",
            type="int",
            default=d["questions_per_persona"],
            min=1,
            max=30,
            group="考试",
        ),
        ParamFieldSchema(
            key="max_validate_rounds",
            label="出题自检轮数",
            description="Persona 出题失败时最多重试次数",
            type="int",
            default=d["max_validate_rounds"],
            min=1,
            max=5,
            group="考试",
        ),
        ParamFieldSchema(
            key="student_answer_batch_size",
            label="作答批大小",
            description="每次 LLM 作答的题目数",
            type="int",
            default=d["student_answer_batch_size"],
            min=1,
            max=50,
            group="考试",
        ),
        ParamFieldSchema(
            key="closed_book_exam",
            label="闭卷考试",
            description="作答时仅允许使用笔记，不给原文",
            type="bool",
            default=d["closed_book_exam"],
            group="学习真实性",
        ),
        ParamFieldSchema(
            key="use_chapter_mastery",
            label="章节掌握模式",
            description="按章节学习：单章闭卷达标后再学下一章（推荐）",
            type="bool",
            default=d.get("use_chapter_mastery", True),
            group="学习真实性",
        ),
        ParamFieldSchema(
            key="chapter_mastery_accuracy",
            label="章节掌握门槛",
            description="本章闭卷加权正确率达到此值才巩固进长期记忆并进入下一章",
            type="float",
            default=d.get("chapter_mastery_accuracy", 0.98),
            min=0.5,
            max=1.0,
            group="学习真实性",
            visible_when_key="use_chapter_mastery",
            visible_when_equals=True,
        ),
        ParamFieldSchema(
            key="short_term_notes_max_chars",
            label="工作记忆上限",
            description="当前章完整工作笔记（学习阶段可查阅；闭卷时仅术语/易错/自测摘录可进考场）",
            type="int",
            default=d.get("short_term_notes_max_chars", 4000),
            min=500,
            max=50000,
            group="学习真实性",
            visible_when_key="use_chapter_mastery",
            visible_when_equals=True,
        ),
        ParamFieldSchema(
            key="long_term_notes_max_chars",
            label="长期记忆总容量",
            description="已掌握章节内化摘要的总容量；闭卷答题的主要依据",
            type="int",
            default=d.get("long_term_notes_max_chars", 6000),
            min=1000,
            max=50000,
            group="学习真实性",
            visible_when_key="use_chapter_mastery",
            visible_when_equals=True,
        ),
        ParamFieldSchema(
            key="student_notes_max_chars",
            label="闭卷记忆总预算",
            description="闭卷时可用的记忆总量（长期内化 + 工作参考层），不等于完整笔记长度",
            type="int",
            default=d["student_notes_max_chars"],
            min=500,
            max=20000,
            group="学习真实性",
        ),
        ParamFieldSchema(
            key="exam_long_term_ratio",
            label="闭卷·长期记忆占比",
            description="闭卷总预算中分配给「已内化长期记忆」的比例（默认 65%）",
            type="float",
            default=d.get("exam_long_term_ratio", 0.65),
            min=0.2,
            max=0.9,
            group="学习真实性",
            visible_when_key="use_chapter_mastery",
            visible_when_equals=True,
        ),
        ParamFieldSchema(
            key="exam_working_layer_ratio",
            label="闭卷·参考层占比",
            description="闭卷总预算中分配给「术语/易错/自测摘录」的比例（非完整笔记，默认 30%）",
            type="float",
            default=d.get("exam_working_layer_ratio", 0.30),
            min=0.05,
            max=0.5,
            group="学习真实性",
            visible_when_key="use_chapter_mastery",
            visible_when_equals=True,
        ),
        ParamFieldSchema(
            key="chapter_review_ratio",
            label="复习题比例",
            description="考试中来自已掌握章节的复习题占比（0–0.5）",
            type="float",
            default=d.get("chapter_review_ratio", 0.1),
            min=0.0,
            max=0.5,
            group="学习真实性",
            visible_when_key="use_chapter_mastery",
            visible_when_equals=True,
        ),
        ParamFieldSchema(
            key="student_notes_study_max_chars",
            label="学习笔记上限（页数模式）",
            description="仅「页数课程模式」下每轮笔记最大长度",
            type="int",
            default=d["student_notes_study_max_chars"],
            min=1000,
            max=50000,
            group="学习真实性",
            visible_when_key="use_chapter_mastery",
            visible_when_equals=False,
        ),
        ParamFieldSchema(
            key="curriculum_pages_per_round",
            label="每轮解锁页数（页数模式）",
            description="仅「页数课程模式」：每轮累积解锁的文档页面数",
            type="int",
            default=d["curriculum_pages_per_round"],
            min=1,
            max=200,
            group="学习真实性",
            visible_when_key="use_chapter_mastery",
            visible_when_equals=False,
        ),
        ParamFieldSchema(
            key="judge_evidence_only",
            label="Evidence 评分",
            description="Judge 仅依据 evidence 原文评分",
            type="bool",
            default=d["judge_evidence_only"],
            group="评分",
        ),
        ParamFieldSchema(
            key="evidence_cap_score",
            label="外推惩罚上限",
            description="答案超出 evidence 时的分数封顶",
            type="float",
            default=d["evidence_cap_score"],
            min=0.5,
            max=1.0,
            group="评分",
        ),
        ParamFieldSchema(
            key="judge_batch_size",
            label="Judge 批大小",
            description="每次 LLM 评分的题目数",
            type="int",
            default=d["judge_batch_size"],
            min=1,
            max=50,
            group="评分",
        ),
    ]
    groups = []
    for f in fields:
        if f.group not in groups:
            groups.append(f.group)

    presets = [
        ParamPresetSchema(
            id="development",
            label="开发调试",
            description="少题量、大批次、快速迭代（默认）",
            values=DEV_PRESET_VALUES,
        ),
        ParamPresetSchema(
            id="production",
            label="生产完整",
            description="150 题首轮、完整自检，接近真实学习闭环",
            values=PROD_PRESET_VALUES,
        ),
    ]
    return ParamSchemaResponse(
        groups=groups,
        fields=fields,
        presets=presets,
        default_preset="development",
    )
